package game.shared.protocol

enum class MessageType {
    JOIN_REQUEST,
    JOIN_ACCEPTED,
    JOIN_REJECTED,
    INPUT_COMMAND,
    INTERACT_COMMAND,
    ATTACK_COMMAND,
    ATTACK_STARTED_EVENT,
    HIT_EVENT,
    DAMAGE_EVENT,
    ENTITY_DIED_EVENT,
    WORLD_SNAPSHOT,
    GAME_EVENT,
    PING_REQUEST,
    PONG_RESPONSE,
}
